### ISSUE TITLE
[Docs]: Dependencies not complete in ReadMe.md and bloated in requirements.txt

### ISSUE THREAD

**Issue by SilverscaleClockwork** [edrisranjbar/AparatDownloader#10]
The README.md doesn't include a full list of dependencies that are required.
For example it's also required to install webdriver_manager.

Therefore i tried to look into the requirements.txt which includes a lot of dependencies that are not even required for testing.

Suggestion:
Add every important module that is required for running into requirements.txt and make a secondary file file for testing requirements.

**Comment by edrisranjbar** [comment]
**Hi @ChinoCodeDemon; Thanks for contributing in this repo.**
`requirements.txt` contains all the requirements for this script; in details. but when you install the main requirements like `selenium`, `webdriver-manager` and `wget`, those sub-modules will be installed as a dependency and you shouldn't worry about it at all. all you should do is `pip install -r requirements.txt`; _That's it!_

and of course `webdriver-manager` is one of the main requirements and i forgot to put it on `dependency list` in readme file. but `unittest` is a dev dependency. I'm not sure it's a good idea to include that in dependencies, because not every person using the script want to actually run tests.
